
restart;
eq1:=Psa-Ps-Q*Rsa;
eq2:=F*Cld*Ppv-Q:
eq3:=Ps-Psv-Q*Rsv;
eq4:=Ppa-Ppv-Q*Rp;
eq5:=F*Crd*Psv-Q;
eq6:=Cp*(Ppa+Ppv)/2+V0p-Vp;
eq7:=Csv*(Psv+Ps)/2-Vsv;
eq8:=Csa*(Psa+Ps)/2+V0s-Vsa;
eq9:=Vsa+Vsv+Vp-Vt;
solve({eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9},{Psa,Ps,Psv,Ppa,Ppv,Q,Vsa,Vsv,Vp});
assign(%);
simplify(Psa/Q);
simplify(Ps/Q);
simplify(Psv/Q);
simplify(Ppa/Q);
simplify(Ppv/Q);
Q;
NULL;
