
from sympy import *
# fm and gm denote the shifted functions
# The other notation should be self-explanatory.

x,f1,h,g1,Delta,k = symbols('x f1 h g1 Delta k',positive = 'true')

f = f1*x/h
fm = f1*(x-Delta)/h
g = g1*x/h 
gm = g1*(x-Delta)/h
       
n0low = f/(g + f)
n0high = f/( fm*g/gm + f + g)
nm1low = fm/( f*gm/g + fm+gm)
nm1high = fm/(fm+gm)

# Calculate the force generated by the n_0 crossbridges
n0int = k*integrate(x*n0low,(x,0,Delta)) + k*integrate(x*n0high,(x,Delta,h))

# Calculate the force generated by the n_{-1} crossbridges
nm1int = k*integrate((x-Delta)*nm1low,(x,Delta,h)) + k*integrate((x-Delta)*nm1high,(x,h,h+Delta))

# Now add the two integrals together to get the total force.
dum1 = factor(simplify(n0int+nm1int))
pprint(dum1)

# Now calculate the isometric force of the Huxley model with a single binding site
dum2 = k*integrate(x*n0low,(x,0,h))
pprint(dum2)

#Subtract the two forces to see which is greater
pprint(factor(simplify(dum1-dum2)))
